/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        "co-background": "#f7f9fb",
        "co-primary": "#004ac6",
        "co-surface-container-low": "#f2f4f6",
        "co-surface-container-lowest": "#ffffff",
        "co-surface-container": "#eceef0",
        "co-tertiary": "#005b7c",
        "co-secondary": "#565e74",
        "co-outline": "#737686",
        "co-outline-variant": "#c3c6d7",
        "co-on-background": "#191c1e",
        "co-on-surface-variant": "#434655",
        "co-primary-fixed-dim": "#b4c5ff",
        "co-error": "#ba1a1a",
        "co-on-primary": "#ffffff",
        "on-error": "#ffffff",
        "secondary-container": "#dae2fd",
        "tertiary": "#005b7c",
        "surface-container-high": "#e6e8ea",
        "primary-container": "#2563eb",
        "inverse-surface": "#2d3133",
        "on-primary-container": "#eeefff",
        "surface-container-low": "#f2f4f6",
        "on-secondary-fixed": "#131b2e",
        "surface-dim": "#d8dadc",
        "on-primary": "#ffffff",
        "surface": "#f7f9fb",
        "on-background": "#191c1e",
        "primary-fixed": "#dbe1ff",
        "outline": "#737686",
        "on-tertiary-fixed": "#001e2c",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary-fixed-variant": "#004c69",
        "on-error-container": "#93000a",
        "background": "#f7f9fb",
        "on-surface-variant": "#434655",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#e1f2ff",
        "tertiary-fixed": "#c4e7ff",
        "on-primary-fixed-variant": "#003ea8",
        "error": "#ba1a1a",
        "surface-container": "#eceef0",
        "on-secondary-container": "#5c647a",
        "inverse-primary": "#b4c5ff",
        "surface-variant": "#e0e3e5",
        "surface-bright": "#f7f9fb",
        "on-secondary-fixed-variant": "#3f465c",
        "tertiary-container": "#00759f",
        "secondary-fixed": "#dae2fd",
        "primary-fixed-dim": "#b4c5ff",
        "surface-container-highest": "#e0e3e5",
        "tertiary-fixed-dim": "#7bd0ff",
        "primary": "#004ac6",
        "on-surface": "#191c1e",
        "secondary": "#565e74",
        "on-primary-fixed": "#00174b",
        "outline-variant": "#c3c6d7",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-tint": "#0053db",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#bec6e0"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-md": "20px",
        "container-padding": "32px",
        "gutter": "24px",
        "base": "8px",
        "stack-sm": "12px",
        "section-gap": "64px"
      },
      fontFamily: {
        "co-inter": ["Inter", "sans-serif"],
        "co-jakarta": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "body-md": ["Inter"],
        "label-sm": ["Inter"],
        "label-md": ["Inter"],
        "headline-md": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}]
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [],
}
