/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        foreground: "hsl(var(--foreground))",
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        "on-primary-container": "#eeefff",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#c1c6db",
        "on-secondary-fixed-variant": "#414658",
        "surface-container": "#ededf9",
        "inverse-primary": "#b4c5ff",
        "secondary": "#585e70",
        "surface-container-low": "#f3f3fe",
        "surface": "#faf8ff",
        "primary": "#004ac6",
        "on-tertiary": "#ffffff",
        "outline": "#737686",
        "inverse-surface": "#2e3039",
        "tertiary": "#005e6e",
        "on-surface": "#191b23",
        "on-tertiary-fixed": "#001f26",
        "primary-fixed": "#dbe1ff",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f0f0fb",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#4cd7f6",
        "background": "#faf8ff",
        "on-background": "#191b23",
        "surface-dim": "#d9d9e5",
        "surface-variant": "#e1e2ed",
        "on-primary-fixed-variant": "#003ea8",
        "primary-fixed-dim": "#b4c5ff",
        "on-error": "#ffffff",
        "surface-container-highest": "#e1e2ed",
        "surface-bright": "#faf8ff",
        "surface-container-high": "#e7e7f3",
        "on-tertiary-fixed-variant": "#004e5c",
        "on-primary-fixed": "#00174b",
        "primary-container": "#2563eb",
        "surface-tint": "#0053db",
        "on-primary": "#ffffff",
        "on-surface-variant": "#434655",
        "secondary-container": "#dde2f8",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#acedff",
        "outline-variant": "#c3c6d7",
        "on-tertiary-container": "#d7f6ff",
        "on-secondary-fixed": "#151b2b",
        "on-secondary-container": "#5e6476",
        "secondary-fixed": "#dde2f8",
        "tertiary-container": "#00788c",
        "on-secondary": "#ffffff"
      },
      borderRadius: {
        lg: "0.5rem",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        DEFAULT: "0.25rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "gutter": "24px",
        "stack-lg": "32px",
        "max-width": "1600px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "container-padding": "32px",
        "unit": "8px"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "label-md": ["JetBrains Mono"],
        "body-sm": ["Inter"],
        "display-lg": ["Plus Jakarta Sans"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
