/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        "on-secondary-container": "#006172",
        "on-tertiary-container": "#eef0ff",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-dim": "#d8dadc",
        "on-background": "#191c1e",
        "primary-fixed-dim": "#b4c5ff",
        "surface-container-low": "#f2f4f6",
        "on-primary-fixed-variant": "#003ea8",
        "tertiary-container": "#656d84",
        "tertiary-fixed": "#dae2fd",
        "secondary-fixed": "#acedff",
        "secondary-container": "#57dffe",
        "on-tertiary-fixed-variant": "#3f465c",
        "outline": "#737686",
        "surface-container": "#eceef0",
        "error-container": "#ffdad6",
        "primary": "#004ac6",
        "on-primary-fixed": "#00174b",
        "secondary": "#00687a",
        "surface-bright": "#f7f9fb",
        "surface-variant": "#e0e3e5",
        "on-surface": "#191c1e",
        "tertiary-fixed-dim": "#bec6e0",
        "surface-container-high": "#e6e8ea",
        "inverse-primary": "#b4c5ff",
        "on-secondary-fixed": "#001f26",
        "tertiary": "#4d556b",
        "surface-container-highest": "#e0e3e5",
        "secondary-fixed-dim": "#4cd7f6",
        "error": "#ba1a1a",
        "inverse-surface": "#2d3133",
        "on-primary-container": "#eeefff",
        "on-primary": "#ffffff",
        "background": "#f7f9fb",
        "outline-variant": "#c3c6d7",
        "on-secondary-fixed-variant": "#004e5c",
        "primary-container": "#2563eb",
        "surface": "#f7f9fb",
        "on-tertiary-fixed": "#131b2e",
        "surface-tint": "#0053db",
        "primary-fixed": "#dbe1ff",
        "on-surface-variant": "#434655",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        // Keep existing colors just in case
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        foreground: "hsl(var(--foreground))",
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "stack_sm": "8px",
        "sidebar_width": "280px",
        "stack_lg": "32px",
        "stack_md": "16px",
        "gutter": "24px",
        "container_padding": "32px"
      },
      fontFamily: {
        "headline-md": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "data-mono": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "500"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "500"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "data-mono": ["16px", {"lineHeight": "24px", "letterSpacing": "0.02em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
